[package]
name = "bigman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
eyre = "0.6.12"
phf = { version = "0.11.2", features = ["macros"]}
rayon = "1.10.0"
smallvec = "1.13.2"
